name: week_6
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  flutter_bloc: ^9.1.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  logger: ^2.6.2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.7.3
  retrofit_generator: ^10.0.6
  lottie: ^3.3.1

dev_dependencies:
  build_runner: ^2.9.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
