name: week_6
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.4
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  logger: ^2.6.2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.7.3
  lottie: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.7.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: ^7.0.8
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
